project_id = "cyzywykgdravxfnhskzq"

[functions.ingest-ot-order]
verify_jwt = false

[functions.accept-user-sync]
verify_jwt = false

[functions.webhook-receiver]
verify_jwt = false

[functions.webhook-outbound-publisher]
verify_jwt = false

[functions.ot-webhook-receiver]
verify_jwt = false

[functions.process-ot-notifications]
verify_jwt = false
